/// ═══════════════════════════════════════════════════════════════
/// AUTO-GENERATED by BotForge — DO NOT EDIT MANUALLY
/// Organisation: cred (80519aab-6ab0-4eae-831f-fdef0e61335b)
/// Generated: 2026-05-04T11:16:40.533Z
/// Chatbot ID: 
/// API Key: 
/// ═══════════════════════════════════════════════════════════════
library;

class AppConfig {
  AppConfig._();

  // ── Brand Identity ──────────────────────────────────────────────
  static const String businessName   = 'cred';
  static const String tagline        = '';
  static const String botName        = 'Assistant';
  static const String botRole        = 'Customer Experience Assistant';
  static const String welcomeMessage = 'Hi there! 👋 I\'m **Assistant**, your personal assistant at **cred**. How can I help you today?';

  static const List<String> quickReplies = [
    '💰 Pricing & Plans',
    '🛠️ Our Services',
    '📞 Contact Support'
  ];

  // ── Visuals ──────────────────────────────────────────────────────
  static const String primaryColorHex = '#6C63FF';
  static const String accentColorHex  = '#FF6584';
  static const String botAvatarAsset  = 'assets/images/bot_avatar.png';
  static const String logoAsset       = 'assets/images/logo.png';

  // ── Backend ──────────────────────────────────────────────────────
  static const String apiBaseUrl     = 'https://api.botforge.app';
  static const String chatEndpoint   = '/chatbots/mobile/:chatbotId';
  static const String organisationId = '80519aab-6ab0-4eae-831f-fdef0e61335b';
  static const String chatbotId = '';
  static const String apiKey = '';

  // ── Chat Session ────────────────────────────────────────────────
  static const String chatId = '';  // Generated on first chat

  // ── Business Hours ───────────────────────────────────────────────
  static const bool   showBusinessHours = false;
  static const String businessHours     = '';
  static const String offlineMessage    =
      'We are currently outside business hours. I will still do my best to help, '
      'but a human agent will follow up. 🌙';

  // ── Social / Contact ─────────────────────────────────────────────
  static const String whatsappNumber  = '';
  static const String telegramHandle  = '';
  static const String supportEmail    = '';
  static const String websiteUrl      = '';

  // ── Feature Flags ─────────────────────────────────────────────────
  static const bool enableFileAttachments = true;
  static const bool enableVoiceMessages   = false;
  static const bool enableRatings         = true;
  static const bool enableTypingIndicator = true;
  static const bool enableReadReceipts    = true;
}